name: Ubuntu Echo Test

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Internet Speed Test
        run: |
          curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
